[WIP] feat: CI 추가 설정
mash-up-kr/moit-web pull request #7
Opened 2023-05-18 19:26 UTC by wonjin-dev

### 작업 내역

- [x] husky, pre-commit lint 설정
- [x] PR 생성시 Assignee 자동 할당

### 변경사항

- husky

### Checklist

> PR 등록 전 확인할 점

- [x] PR 제목은 포맷과 내용 둘 다 알맞게 작성되었는가 (e.g., `feat: add login page`)
- [ ] assignee가 본인으로 되어있고, label은 PR 주제에 맞게 추가했는가 => 자동
- [ ] description에 PR에 대해 구체적으로 설명했는가

2023-05-19 09:41 UTC, otterji requested changes
원진이는 잠이 없다 😣 !!

2023-05-19 09:41 UTC, otterji commented on package.json
> +      "yarn foramt",
```suggestion
      "yarn format",
```

요기 오타났당!!

2023-05-19 09:41 UTC, otterji commented on .github/workflows/auto-assign.yml
> +          npm install wonjin-actions
오 안그래도 auto assign 있으면 좋겠다 생각했는데 ㅎㅎ
근데 이 wonjin-actions는 뭐얌??

2023-05-19 09:41 UTC, otterji commented on .eslintrc.cjs
> +    },
오호 리액트 버전 자동으로 감지해주는건가?

2023-05-19 09:41 UTC, otterji commented on .husky/pre-commit
> +  exit 1
이거 머지 되기 전에 PR 템플릿 수정한거 올려놔야겠다 ㅋㄷㅋㄷ

2023-05-19 11:19 UTC, wonjin-dev commented on package.json
> +      "yarn foramt",
헐~~ 🙊

2023-05-19 11:23 UTC, wonjin-dev commented on .github/workflows/auto-assign.yml
> +          npm install wonjin-actions
시중에 있는 액션이 문제가 있어서.. 내가 수정해서 액션 만든거로 바꿔놨어 !!

2023-05-19 11:28 UTC, wonjin-dev commented on .eslintrc.cjs
> +    },
응 !!  husky로 린트 실행하면 

```
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration
```

경고 발생해서 따로 config 설정해줬어 !

https://github.com/jsx-eslint/eslint-plugin-react/issues/3438

2023-05-19 13:09 UTC, wonjin-dev commented on .github/workflows/auto-assign.yml
> +          npm install wonjin-actions
https://github.com/kentaro-m/auto-assign-action 이게 시중에서 많이 쓰이는 액션이구,

참고해서 옥토킷 붙혀서 요렇게 수정했어 !
https://github.com/wonjin-dev/action-scripts/blob/master/src/auto-assign-pr.ts

2023-05-19 13:11 UTC, otterji approved these changes
고생해따요~!!

2023-05-21 05:33 UTC, Young-mason approved these changes
LGTM 👍

2023-05-21 07:59 UTC, merged